### ISSUE TITLE
Additional command line options

### ISSUE THREAD

**Issue by carlosfrodriguez** [whity/atom-linter-perlcritic#10]
Hi @whity,

I'm trying to add --verbose 8 as an option to the command line but It is not working I tried several formats, can you please tell me the correct way to put those params?

Thank you

**Comment by whity** [comment]
Hi @carlosfrodriguez,

When I've some time I'll look at it, but should've worked the you tried.

**Comment by carlosfrodriguez** [comment]
Hi @whity 

I manage to make it work by adding a .perlcriticrc file with the options and I realize that --verbose 8 has a different format and then it was not recognized by the RegEx, so I lower it to --verbose 4 and looks like working

However I also found in the code that you are sending the Type as the perl critic level (in my case 'stern') unfortunately the linter does not have the stytes for that and there is no decoration for example to highlight in red or so, then I change the type to Error or Warning and it works very good, but I don't like the idea of having a 'patched' version of your linter. Any step by step recommendation? I read that you can add somewhere the styles for custom types to the linter, but I have no idea where to do it.

**Comment by whity** [comment]
Hi @carlosfrodriguez 

I also use the file '.perlcriticrc' for configure it's behaviour. 
Regarding the option "linter-perlcritic.level", that's the level for the linter not perlcritic severity.
You can change in the '.perlcriticrc' file and than customise the option 'linter-perlcritic.regex'.

**Comment by carlosfrodriguez** [comment]
Hi @whity 

ahhhhhhhh! :-) I see linter-perlcritic.level haha. Cool now it is perfect.

Maybe a couple of hints in the Raedme file for Dummy users as me could be a nice addition :-)

Than you, I think you can close this issue then.

**Comment by whity** [comment]
Hi,

I'm glad you make it work, and you're right about the doc, :)
